spring.application.name=reminder

# H2
spring.datasource.url=jdbc:h2:file:./data/reminder
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# CORS
spring.mvc.cors.mappings[/api/**].allowed-origins=http://localhost:3000
spring.mvc.cors.mappings[/api/**].allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.mvc.cors.mappings[/api/**].allowed-headers=*
